export const UZMANLIK_ALANLARI = [
  "Aile Hukuku",
  "Boşanma Hukuku",
  "Ceza Hukuku",
  "İş Hukuku",
  "Ticaret Hukuku",
  "Şirketler Hukuku",
  "Gayrimenkul Hukuku",
  "İcra ve İflas Hukuku",
  "Miras Hukuku",
  "Sigorta Hukuku",
  "Vergi Hukuku",
  "İdare Hukuku",
  "Fikri Mülkiyet Hukuku",
  "Sağlık Hukuku",
  "Bilişim Hukuku",
  "Trafik Kazaları Hukuku",
  "Tüketici Hukuku",
  "İnşaat Hukuku",
  "Yabancılar ve Vatandaşlık Hukuku",
  "İnsan Hakları Hukuku",
];
